### ISSUE TITLE
Not using OAuth2AuthorizationCodeBearer?

### ISSUE THREAD

**Issue by rafalkrupinski** [lukasthaler/fastapi-oauth-examples#1]
CAN'T THANK YOU ENOUGH for these examples.
Forgive the all-caps, but I really mean it :)

I noticed you didn't use FastAPIs OAuth2AuthorizationCodeBearer... Is it because your code is older than that class or is that class intended for implementing OAUth2 Authorization Server and not Resource Server, or yet another reason?

Best Regards

**Comment by lukasthaler** [comment]
Hi there,
sorry for the late reply, I don't really monitor this repo. Happy it helped you 😄

As for your question - the simple truth is that when I built this, I was relatively new to FastAPI and unaware of a lot of its functionality. If I were to rewrite this today, I'd probably do a few things differently

**Comment by rafalkrupinski** [comment]
didn't you answer me already? :)
I guess I better close the issue.

> If I were to rewrite this today, I'd probably do a few things differently

👍
